### ISSUE TITLE
DSCLOCK.SYS doesnt recognize the RTC8088 3.0 Card.

### ISSUE THREAD

**Issue by explit7** [spark2k06/RTC8088#9]
Somehow it does not work for me.
I flashed the latest SPLD on a new ATF16V8B Chip.
It is recognized by the Micro8088 BIOS only when i set the DIP-Switches to On On On or Off Off Off.
Otherwise it is not recognized by the Micro8088 BIOS and its always Absent in BIOS.

DSCLOCK.SYS doesnt recognize it when i use Autodetection or when i use the Parameter 0X2C0
GET_RTC and SET_RTC recognized it on Port 02c0.
Very weird.

I have usual Micro8088 System with following Carts:
XTIDE, Adlib Card, Cycle Logic CGA-Graphic Card, 2xSerial, 1xParallel Controller 16C552, RTC8088 3.0

Any suggestions, what else i can test?

![RTC1](https://github.com/spark2k06/RTC8088/assets/11852348/95eda04b-da57-4179-bebf-a374b0092183)
![RTC2](https://github.com/spark2k06/RTC8088/assets/11852348/2d7503f1-b668-447e-a174-1b0e4e395bf7)
![RTC3](https://github.com/spark2k06/RTC8088/assets/11852348/dda800aa-805e-4aaf-bf41-89be699f5aec)

_Originally posted by @explit7 in https://github.com/spark2k06/RTC8088/issues/8#issuecomment-2166947224_

**Comment by explit7** [comment]
OK found something weird. When i set the RTC8088 DIP-Switches to 02C0 - it is not recognized by the Micro8088 BIOS, but it recognized by the DSCLOCK.SYS.

Very weird...

**Comment by skiselev** [comment]
The 8088 BIOS code and this DSCLOCK.SYS code are mutually exclusive:

- The 8088 BIOS only supports RTC on port 0x70.
- The DSCLOCK.SYS driver does not support port 0x70. RTC8088 should be configured to use other ports when using DSCLOCK.SYS driver

Basically there are two use case:
1. The 8088 BIOS on an FE2010A or a PT8010AF based system (Micro 8088, NuXT). In this case, the RTC should be configured to port 0x70, and the 8088 BIOS RTC support should be used.
2. RTC8088 used with any other systems, e.g., the original IBM PC or XT. In this case most likely the RTC will not work on port 0x70 because the ports below 0x100 are allocated for the on-board devices. When trying to read these ports, the ISA bus data transceiver on the system board will be configured in the wrong direction - from the system board to the ISA bus. This will create a bus contention and might be even dangerous, as both said transceiver and the RTC will try to drive the data bus... Therefore, for these systems, other ports - 0x240, 0x2A0, 0x2C0, 0x340, 0x3A0, or 0x3C0 should be used instead. Also, since the system BIOS on these systems wouldn't have a built-in RTC support, the DSCLOCK.SYS should be used.

There are some other [systems and motherboards based on the FE2010A or the PT8010AF chipsets](https://github.com/skiselev/Proton_Turbo_XT), where the RTC can be safely configured on port 0x70... But likely this is a minority of the motherboard, and given the risks described above, I deliberately decided not to enable port 0x70 support in DSCLOCK.SYS... It is not that difficult to enable port 0x70 support though, and I can do that if you feel that it is desired.

I'll update your https://github.com/skiselev/8088_bios/issues/71 issue separately, as it doesn't have anything to do with the DSCLOCK.SYS driver.

**Comment by explit7** [comment]
OK, i understand, @skiselev  For me this was not clear, why in Micro8088 BIOS the RTC should be default on 0x70, when DSCLOCK.SYS can't detect it on 0x70.
Now i understand, that DSCLOCK.SYS is not meant for use with Micro8088 and NuXT.

My wish was ,that the RTC is detected in Micro8088 and detected by DSCLOCK.SYS.
If you can change DSCLOCK.SYS to enable detection on 0x70 Port -that would be nice.
If not - i will stay on GET_RTC.EXE and SET_RTC.EXE

The both tools detect my RTC on Port 0x2C0 (what is wrong), but they work.
Of course DSCLOCK.SYS would me more reliable.
Maybe put a small check? When FE2010A / PT8010AF is detected - look on Port 0x70 ?

Thanks

**Comment by skiselev** [comment]
It's not a problem to add port 0x70 support. Detecting FE2010A / PT8010AF might not be trivial... The 8088 BIOS does that, but it already knows that it will find either one of these chipsets, and just checks for a small difference in their behavior

**Comment by explit7** [comment]
Yes, maybe changinging DSCLOCK.SYS to support 0x70 Port would be the easiest solution!

**Comment by skiselev** [comment]
I added I/O port 0x70 support in the latest driver. It doesn't show in the usage/help, because I think it is somewhat of an exception, and I don't want users to get bad ideas ;)

**Comment by explit7** [comment]
> I added I/O port 0x70 support in the latest driver. It doesn't show in the usage/help, because I think it is somewhat of an exception, and I don't want users to get bad ideas ;)

Thanks @skiselev for your change and thanks for @spark2k06 for quick merging!
DSCLOCK.SYS now works on my Port 0x70 and seems to work more reliable then previous combo (GET_RTC / SET_RTC).
GET_RTC / SET_RTC have worked also, but detected the RTC8088 Module on Port 02C0, which was wrong...

I close the issue now.
